# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Prepare Environment File
      run: |
        BRANCH_NAME=${{ github.ref_name }}
        echo "Detected branch: $BRANCH_NAME"
        
        if [ "$BRANCH_NAME" == "main" ] || [ "$BRANCH_NAME" == "main-deploy" ]; then
          # For development deployment
          SSH_PRIVATE_KEY=${{ secrets.DEV_SSH_PRIVATE_KEY }}
          SERVER_IP=${{ secrets.DEV_SERVER_IP }}
        else
          echo "No specific environment file defined for branch '$BRANCH_NAME'. Skipping copy."
        fi

    - name: Print environment variables for debugging
      run: |
        echo "Branch: $BRANCH_NAME"
        echo "Server IP: $SERVER_IP"
        
    # Step 2: Set up SSH
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

    # Step 3: Run SSH commands
    - name: Run SSH command
      run: |
        ssh -o StrictHostKeyChecking=no user@your.server.com "echo 'Hello from GitHub Actions!'"
    
